#!/bin/bash
# Job name
#PBS -N times_benchmark

# Output and error file
#PBS -o results/times_benchmark.out
#PBS -e results/times_benchmark.err

# Queue name
#PBS -q short_cpuQ

# Set the max wall time
#PBS -l walltime=06:00:00

# Set the other things
#PBS -l select=1:ncpus=64:mem=32gb

# Load module
module load gcc91 || { echo "module load failed"; exit 1; }

# Select the working directory
cd "$PBS_O_WORKDIR" || { echo "PBS_O_WORKDIR not set or inaccessible"; exit 1; }

# Compile and run

EXECUTABLE="./spmv"
MATRICES=(
    "af23560.mtx"
    "twotone.mtx"
    "tmt_unsym.mtx"
    "atmosmodl.mtx"
    "Freescale1.mtx"
)
DATA_DIR="data"
MODES=(
    #"seq" handled separately
    "static"
    "dynamic"
    "guided"
)
CHUNK_SIZE=(1 10 100 1000)
THREADS=(1 2 4 8 16 32 64)
NUM_RUNS=10
RESULTS_DIR="results"
RESULTS_CSV="$RESULTS_DIR/time_results.csv"

# Compile the program
gcc -Wall -O3 -fopenmp src/main.c src/matrix.c src/mmio.c -o spmv -lm

# Clear results file
echo "Matrix,Mode,ChunkSize,Threads,Time_ms" > $RESULTS_CSV

for MATRIX_NAME in "${MATRICES[@]}"
do
    MATRIX_FILE="$DATA_DIR/$MATRIX_NAME"

    # Sequential version
    echo "Running: $MATRIX_NAME, seq, NA, 1 thread" # matrix_name, mode, chunk_size, threads
    
    # spmv matrix_file mode chunk_size threads
    TIME_MS=$($EXECUTABLE $MATRIX_FILE seq 1 1 $NUM_RUNS | grep "Time:" | awk '{print $2}')
   
    echo "$MATRIX_NAME,seq,NA,1,$TIME_MS" >> $RESULTS_CSV

    # Loop over modes
    for MODE in "${MODES[@]}"
    do
        # Loop over chunk sizes
        for CHUNK in "${CHUNK_SIZE[@]}"
        do
            # Loop over threads
            for T in "${THREADS[@]}"
            do 
                echo "Running: $MATRIX_NAME, $MODE, $CHUNK, $T threads"

                TIME_MS=$($EXECUTABLE $MATRIX_FILE $MODE $CHUNK $T $NUM_RUNS | grep "Time:" | awk '{print $2}')

                echo "$MATRIX_NAME,$MODE,$CHUNK,$T,$TIME_MS" >> $RESULTS_CSV
            done
        done
    done
done

echo "Data saved in $RESULTS_CSV"