#!/bin/bash
# Job name
#PBS -N strong_scaling

# Output and error file
#PBS -o D2/results/strong_scaling.out
#PBS -e D2/results/strong_scaling.err

# Queue name
#PBS -q short_cpuQ

# Send email when the job is finished
#PBS -M agnese.marchesini-1@studenti.unitn.it                                             
#PBS -m e

# Set the max wall time
#PBS -l walltime=02:00:00

# Set the other things
#PBS -l select=2:ncpus=64:mpiprocs=64:mem=32gb

module load gcc91 || { echo "module load failed"; exit 1; }
module load mpich-3.2.1--gcc-9.1.0 || { echo "module load failed"; exit 1; }

cd "$PBS_O_WORKDIR" || { echo "PBS_O_WORKDIR not set or inaccessible"; exit 1; } # go to the dir where the qsub was run

EXECUTABLE="./spmv"
MATRICES=(
    "venkat25.mtx"
    "atmosmodl.mtx"
    "rajat31.mtx"
    "circuit5M.mtx"
    "cage15.mtx"
)
DATA_DIR="D2/data/strong_scaling_matrices"
RESULTS_DIR="D2/results"
STRONG_SCALING_CSV="$RESULTS_DIR/strong_scaling.csv"

mpicc -O3 -Wall D2/src/main.c D2/src/matrix.c D2/src/mmio.c D2/src/ghost_entries.c D2/src/distribution.c -o spmv || { echo "Compilation failed"; exit 1; }
chmod +x ./spmv

# Setup
mkdir -p $RESULTS_DIR

echo "Matrix,Processes,T_Comm,T_Comp,Tot_Time,GFLOPS,Mem_MB,NZ_Min,NZ_Max,NZ_Avg,Volume_MB" > $STRONG_SCALING_CSV

for MATRIX_NAME in "${MATRICES[@]}"
do
    for P in 1 2 4 8 16 32 64 128
    do
        echo "Running with $P processes..."

        OUTPUT=$(mpirun -np $P $EXECUTABLE "$DATA_DIR/$MATRIX_NAME")

        STATS_LINE=$(echo "$OUTPUT" | grep "STATS:")
        
        # printf("STATS: %f %f %f %f %f %d %d %f %f", max_comm, max_comp, total_time, gflops, global_mem, min_nz, max_nz, avg_nz, max_comm_volume/(1024.0*1024.0));

        TIME_COMM=$(echo "$STATS_LINE" | awk '{print $2}')
        TIME_COMP=$(echo "$STATS_LINE" | awk '{print $3}')
        TOT_TIME=$(echo "$STATS_LINE" | awk '{print $4}')
        GFLOPS=$(echo "$STATS_LINE" | awk '{print $5}')
        MEM_MB=$(echo "$STATS_LINE" | awk '{print $6}')
        NZ_MIN=$(echo "$STATS_LINE" | awk '{print $7}')
        NZ_MAX=$(echo "$STATS_LINE" | awk '{print $8}')
        NZ_AVG=$(echo "$STATS_LINE" | awk '{print $9}')
        VOLUME=$(echo "$STATS_LINE" | awk '{print $10}')

        echo "$MATRIX_NAME,$P,$TIME_COMM,$TIME_COMP,$TOT_TIME,$GFLOPS,$MEM_MB,$NZ_MIN,$NZ_MAX,$NZ_AVG,$VOLUME" >> $STRONG_SCALING_CSV
    done
done

